### ISSUE TITLE
Dash character removed in Word Export

### ISSUE THREAD

**Issue by inadorel** [securityroots/dradispro-tracker#212]
Whenever I use the - (dash) character in an export to docx - it is removed....  So for example text such as "Reference - http://xxxx) is being replaced by "Referencehttp://xxxx).  It looks ok in the browser within Dradis, it is only during the export to Word that it is being corrupted.

**Comment by stephenreda** [comment]
I know that when you import an issue , f.e. from a mediawiki article, single enters are also removed after export. You need to enter two enter's in mediaWiki. But I presume that this is not related to your issue at all.

**Comment by inadorel** [comment]
It looks perfectly normal in Dradis (viewing the entry in a browser) - it is only when exported to the Word document that the error occurs.  This is coming out of a custom database rather than MediaWiki.  But interesting to know and I will try playing with adding extra enters on my next report.

**Comment by etdsoft** [comment]
@inadorel, will have a look. This definitely sounds like something we can test for in a unit test to find out what the problem is.

@stephenreda I think that the problem you described re: "single enters" has more to do with Textile formatting than with the import process and the distinction Textile makes between "new lines" and "new paragraphs", more info:
http://securityroots.com/dradispro/support/guides/word_reports/styles.html#new-lines

**Comment by etdsoft** [comment]
Implemented, will ship in the next release / rc.
