### ISSUE TITLE
error loading word doc

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#270]
Just got these errors loading a word doc created through the export:

![dradis_error](https://cloud.githubusercontent.com/assets/117081/8335290/b86eee40-1a94-11e5-81db-7dc84a2ee0de.png)

![dradis_error2](https://cloud.githubusercontent.com/assets/117081/8335374/264dca6c-1a95-11e5-99d6-1f9c595750d2.png)

The document then fails to open.

I'll mail you more info later.

**Comment by etdsoft** [comment]
The telling part is the first one `</tc>` it means that there is a table in the template with a cell that has a single content control (and no other content).

In your project, for whatever reason, you're not providing the content for that control (typo in field name, missing field, etc.) and as a result the <tc></tc> is empty (no content). However this doesn't sit well with word, the spec says that a <tc> always needs to have some content (at least a <p> element) and that's why it's screaming at you.

If you `vi dradis-word_report-65.docx` and open the ./word/document.xml part around that location (line 8, Column 12357) you'll see what the issue is, what the table cell is and hopefully can fix the data in Dradis.

Since this is a template-specific issue I'm inclined to close... thoughts?

**Comment by digininja** [comment]
Leave it open and I'll reply with what I find and how I fix it as it may
help others

**Comment by digininja** [comment]
There are no <tc> or </tc> in the document. That particular column is in the middle of a line of text that is surrounded by a new line on either side and comes after a list and before some bold text.

I just tried removing the list, I now get the first error and the offer to fix the document, after that it opens fine. The person I'm working with says she has seen problems with stuff after lists when she was setting the template up.

**Comment by etdsoft** [comment]
This is a template/data error that isn't related to the reporting engine. Closing for now.
