### ISSUE TITLE
"The page you were looking for doesn't exist." error in wrong place

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#314]
Follow these steps:

Open a tab and go into a project
Select a node
Open a second tab and change project
In the first tab select any note or refresh the page

You get a generic "The page you were looking for doesn't exist." error. I think this should be some kind of styled warning that something has changed and that you can't view the page you are trying to view.

**Comment by TheDauntless** [comment]
There seems to be some over-reliance on data stored in the session. If you start two separate sessions, you can work on two projects at once. We are mostly experiencing this issue when copy/pasting between two reports.

I would also like to change this from "wrong error styling" to "make it possible to have this workflow, instead of throwing an error".

**Comment by rachkor** [comment]
Thanks @digininja and @TheDauntless! Dradis is currently configured to work on one project at a time (per user/session). But, I've added this to our idea backlog to investigate adding in the future.
